services:
  # Backend Service
  - type: web
    name: darius-birthday-backend
    env: python
    buildCommand: cd server && pip install -r requirements.txt
    startCommand: cd server && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5000

  # Frontend Service  
  - type: web
    name: darius-birthday-frontend
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18